### ISSUE TITLE
[BUG] Can't create a sibling

### ISSUE THREAD

**Issue by dreamwhite** [corpnewt/ProperTree#29] opened 2020-05-18 11:26 UTC
Hi there, I'm experiencing this type of bug while using ProperTree. I'm using the latest version aka commit nr. 48d039d

The steps to reproduce the bug are:

1. Create a father entry
2. Right click on it and click on "New sibling of <FATHER ENTRY>"

The child entry should be "inside" the father one. Am I wrong?

Below a screenshot of what I'm talking about    

![Screenshot 2020-05-18 at 13 18 52](https://user-images.githubusercontent.com/17933708/82207438-20f6f680-990a-11ea-9003-f40dad4c1ccb.png)

**Comment by corpnewt** [comment] 2020-05-18 14:55
Well, there are a couple issues with your approach:

1. A `String` is not a collection, and does not support children.  The parent node's type must be either `Dictionary` or `Array`
2. The "New sibling of ..." contextual menu item adds a new _sibling_, not a _child_.  Siblings exist on the same level as the item you clicked and they share a common parent node (see the outline below):
```
Parent
├── Child 1 (Child of Parent)
└── Child 2 (Child of Parent, and sibling of Child 1)
     └── Child 3 (Child of Child 2)
```
3. If you right clicked a `Dictionary` or `Array` - you would also have a "New child under..." contextual menu item that would add a new child to the right-clicked node (example below):
![image](https://user-images.githubusercontent.com/12772521/82227119-f5b1de80-98ec-11ea-8c78-1a430b0fb793.png)
The result of adding that new child would look like the following - which is the behavior you're looking for:
![image](https://user-images.githubusercontent.com/12772521/82227560-91dbe580-98ed-11ea-88e9-b280143752e6.png)

Given the structure and functionality of the items allowed in plists - the script is acting as it should, and I'll close this issue as it's not a bug with the script, but by design.

-CorpNewt

**Closed by corpnewt** 2020-05-18 14:55 UTC
