### ISSUE TITLE
Unable to Run ProperTree on Windows 10

### ISSUE THREAD

**Issue by fakiehmaulana** [corpnewt/ProperTree#87] opened 2021-05-22 14:41 UTC
ProperTree.bat not working on windows 10 20H2

**Comment by corpnewt** [comment] 2021-05-24 13:47
Hey there - can you give any more info regarding it?

Do you have python installed?  If you run `python ProperTree.command` in cmd, does it function as intended?

-CorpNewt

**Comment by datta30** [comment] 2021-05-28 17:19
raceback (most recent call last):
  File "C:\Users\MYUSERNAME\Downloads\ProperTree-master\ProperTree.command", line 5, in <module>
    import Tkinter as tk
ModuleNotFoundError: No module named 'Tkinter'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\MYUSERNAME\Downloads\ProperTree-master\ProperTree.command", line 11, in <module>
    import tkinter as tk
ModuleNotFoundError: No module named 'tkinter'

Script exited with error code: 1

Press [enter] to exit...

This is the error I get when I run ProperTree.bat

**Comment by corpnewt** [comment] 2021-05-28 17:28
Do you have a slim or custom python install? Tkinter is the UI module used, and it comes packaged with Python from python.org.

-CorpNewt

**Comment by datta30** [comment] 2021-05-29 10:46
I used the Microsoft store version before now I removed it and installed python from python.org and it works now and there is no issue with Windows 10 20H2 but the problem was caused maybe because of the Microsoft Store Python app, so you can close this issue now

You can close this Issue @corpnewt

**Closed** 2021-06-08 14:25 UTC
